title: Petroulaaaa Alexaki # your name (or website title) here
logo: #"/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 First description 
 Second description
javascript , React , Node.js , Express , MongoDB , API's , htlm , css
#The last 5 years I have been working as a technical support Analyst for Infor ERP Software company. 
#I have experience in researching and software troubleshooting; debugging code and administering systems. 
#I work well under high stress and I am used in quick learning about product updates and new technologies. 
#My aspiration is to work in software development.
 

javascript , React , Node.js , Express , MongoDB , API's , htlm , css


  
  
theme: minima
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
